SELECT
  *
FROM
  "BRIGHT"."COFFEE"."SHOP"
LIMIT
  10;

  SELECT 
    PRODUCT_CATEGORY,
    PRODUCT_TYPE,
    PRODUCT_DETAIL,
    STORE_LOCATION,
    TRANSACTION_DATE,
    DAYNAME(TRANSACTION_DATE) AS DAY_NAME,
    MONTHNAME(TRANSACTION_DATE) AS MONTH_NAME,
    
    CASE 
        WHEN TRANSACTION_TIME BETWEEN '06:00:00' AND '11:59:59' THEN 'MORNING (6:00–11:59)'
        WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '15:59:59' THEN 'AFTERNOON (12:00–15:59)'
        WHEN TRANSACTION_TIME BETWEEN '16:00:00' AND '19:59:59' THEN 'EVENING (16:00–19:59)'
        ELSE 'NIGHT (20:00–05:59)'
    END AS TIME_BUCKET,
    
    CASE 
        WHEN DAYNAME(TRANSACTION_DATE) IN ('SATURDAY', 'SUNDAY') THEN 'WEEKEND'
        ELSE 'WEEKDAY'
    END AS DAY_CLASSIFICATION,
    
    COUNT(DISTINCT TRANSACTION_ID) AS NUMBER_OF_TRANSACTIONS,
    SUM(TRANSACTION_QTY) AS TOTAL_QUANTITY_SOLD,
    SUM(TRANSACTION_QTY * UNIT_PRICE) AS REVENUE,
    ROUND(SUM(TRANSACTION_QTY * UNIT_PRICE) / 
          COUNT(DISTINCT TRANSACTION_ID), 2) AS AVG_REVENUE_PER_TRANSACTION

FROM BRIGHT.COFFEE.SHOP

WHERE TRANSACTION_DATE >= '2023-01-01'

GROUP BY 
    PRODUCT_CATEGORY,
    PRODUCT_TYPE,
    PRODUCT_DETAIL,
    STORE_LOCATION,
    TRANSACTION_DATE,
    TIME_BUCKET,
    DAY_CLASSIFICATION

ORDER BY REVENUE DESC;

SELECT DISTINCT PRODUCT_DETAIL
FROM BRIGHT.COFFEE.SHOP
ORDER BY  PRODUCT_DETAIL ;
